name: LHCI Test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: lighthouse mobile audit
        run: yarn lhci:mobile
