name: LHCI Test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn run build

      - name: lighthouse mobile audit
        run: yarn lhci:mobile
